name: 'Commit'
description: 'Commit changes in the local repository to the current branch'
inputs:
  message:
    description: 'The commit message'
    required: true
runs:
  using: "composite"
  steps:
    - id: commit
      name: Commit

      run: |
        git config --global user.email ${{ inputs.email_username }}
        git config --global user.name ${{ inputs.username }}
        git config pull.rebase false
        git status
        git pull origin $GITHUB_REF
        git add ./
        timestamp=$(date -u)
        git commit -m "${{ inputs.message }}: ${timestamp}" && git push || true
      shell: bash
