name: 'Commit'
description: 'Commit changes in the local repository to the current branch'
inputs:
  message:
    description: 'The commit message'
    required: true
runs:
  using: "composite"
  steps:
    - id: commit
      name: Commit
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        git config --global user.email $EMAIL_USERNAME
        git config --global user.name $USERNAME
        git config pull.rebase false
        git status
        git pull origin $GITHUB_REF
        git add ./
        timestamp=$(date -u)
        git commit -m "${{ inputs.message }}: ${timestamp}" && git push || true
      shell: bash
