# This is a basic workflow to help you get started with Actions

name: Acquire weekly Albuquerque building permits
# Controls when the action will run.
on:
  schedule:
    # every Sunday at 10:00 pm UTC/8:00 PM in Albuquerque, NM
    - cron:  '0 22 * * SUN'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  acquire_csv:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
      - uses: actions/checkout@main

      - name: Setup Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        uses: ./.github/actions/install-pipenv

      - name: Run
        run: |
          pipenv run python abq-building-permits/1-acquire-permit-data.py

      # If any new data was fetched, create a new commit to the repo.
      - name: Commit data to repo.
        uses: ./.github/actions/commit
        if: always()
        with:
            message: Acquired ABQ building permits csv
