name: Acquire weekly USDA report on New Mexico crops forecast
on:
  schedule:
    - cron:  '0 13 * * 1'
  workflow_dispatch:

jobs:
  acquire_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        uses: ./.github/actions/install-pipenv

      - name: Run
        run: |
          pipenv run python usda-nm-crop-progress/1-acquire-nm-crop-progress.py

      # If any new data was fetched, create a new commit to the repo.
      - name: Commit data to repo.
        uses: ./.github/actions/commit
        if: always()
        with:
            message: Acquired latest NM Crop Progress Report pdf
            email_username: ${{ secrets.EMAIL_USERNAME }}
            username: ${{ secrets.USERNAME }}
