name: Acquire weekly USDA report on New Mexico crops forecast
on:
  schedule:
    - cron:  '0 13 * * 1'
  workflow_dispatch:

jobs:
  acquire_csv:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so your job can access it
      - name: Checkout
      uses: actions/checkout@main

      # https://github.com/marketplace/actions/install-python-pipenv-and-pipfile-packages
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v1
        with:
          python-version: '3.8'

      - name: Run
        run: |
          pipenv run python usda-nm-crop-progress/1-acquire-nm-crop-progress.py

      # If any new data was fetched, create a new commit to the repo.
      - name: Commit data to repo.
        uses: ./.github/actions/commit
        if: always()
        with:
            message: Acquired latest NM Crop Progress Report pdf
            email_username: ${{ secrets.EMAIL_USERNAME }}
            username: ${{ secrets.USERNAME }}
