name: Acquire Bernalillo County 2021-11-02 election results every 15 minutes
on:
  schedule:
    - cron:  '*/15  * * * *'

jobs:
  acquire_csv:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so your job can access it
      - uses: actions/checkout@main

      # https://github.com/marketplace/actions/install-python-pipenv-and-pipfile-packages
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v1
        with:
          python-version: '3.8'

      - name: Run
        run: |
          pipenv run python bernco-2021-11-02-election-results/1-acquire-bernco-results.py

      # If any new data was fetched, create a new commit to the repo.
      - name: Commit data to repo.
        uses: ./.github/actions/commit
        if: always()
        with:
            message: Acquired latest Bernco election results from 2021-11-02
            email_username: ${{ secrets.EMAIL_USERNAME }}
            username: ${{ secrets.USERNAME }}
